---
- hosts: all
  become: true

  tasks:
    - name: Check if docker is installed
      ansible.builtin.command: docker --version
      register: docker_output

    - name: Debug the registered output
      ansible.builtin.debug:
        var: docker_output
    - name: Debug just the stdout
      ansible.builtin.debug:     
        msg: "{{ docker_output.stdout }}"

