- hosts: webservers
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started

    - name: Ensure Nginx is enabled to start at boot
      service:
        name: nginx
        enabled: yes
